#!/bin/sh -e

if ! id "${USERNAME}" >/dev/null 2>&1; then
    echo "Setting credentials to ${USERNAME}"
    adduser -s /bin/sh -h /ftp  -D "${USERNAME}"
    echo "${USERNAME}:${PASSWORD}" | chpasswd
fi

echo "Starting proftpd"
exec proftpd --nodaemon
